### PR TITLE
Updated Error Messages and Bug fixes

### LINKED ISSUE #227: Better Error Messages
We should return better Error Messages.
For example:
Instead of 'Oops ! Something went wrong …' we could use 'Only E-Mails connected to a Google Account are valid'.

### PR DESCRIPTION
**Pull request by Fankhauser-Dominik**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #227

Test URLs:

- Before: https://main--eds-self-service-website--headwire-edge-delivery.aem.live/
- After: https://errors--eds-self-service-website--headwire-edge-delivery.aem.live/

### CODE REVIEW

File: blocks/site-details/renderSiteSpreadsheets.js
Comment (DriftingSands) [inline blocks/site-details/renderSiteSpreadsheets.js:1]: I know it's not in this PR, but we might as well fix it here:
Lines `:136` & `:139` interpolate the `path` variable which could be malicious if an author writes XSS code into the sheet. Plus the html that makes the link wouldn't work if the code for a toast is changed like I commented earlier!

File: scripts/dialogs.js [hunk 1]
```diff
@@ -17,6 +17,12 @@ loadCSS(`${window.hlx.codeBasePath}/styles/dialogs.css`);
  * @returns {HTMLDialogElement} The created dialog element.
  */
 export const createDialog = (contentDiv, buttons, { open = true, onCloseFn, fullscreen, surviveClose = false } = {}) => {
+  // makes sure, that only one dialog element exists at a time
+  const existingDialog = document.querySelector('dialog');
+  if (existingDialog) {
+    return existingDialog;
```
Comment (DriftingSands) [inline scripts/dialogs.js:23]: Is this return needed? I think it could make debugging confusing if there is an existing dialog hidden somewhere and you are getting a dialog you didn't setup.

Afterall one of the options for a dialog (`open:false`) allows you to create the dialog while keeping it hidden

**Review by DriftingSands — CHANGES_REQUESTED** [review]
