### PR TITLE
fixing some XXS vulnerabilities

### LINKED ISSUE #132: Potential XSS vulnrabilities
"The EDS way" of doing things is to write larger block structures as HTML and add it with `.innerHTML`. In a few places we add user defined strings, like site description.
This needs to be fixed

### PR DESCRIPTION
**Pull request by DriftingSands**
Fixing multiple places where XXS could be exploited. Hopefully found them all
Fix #132

### CODE REVIEW

File: blocks/dashboard/renderSiteList.js [hunk 1]
```diff
@@ -53,23 +53,40 @@ async function fetchProjects(token, type = 'googleDrive', scrollTo = false) {
...
-            </ul>
-            ${paginator(pagination.totalItems, currentLimit, actualPage)}
-          `;
+    ${title}
+    <ul class="my-sites-overview" data-totalitems=${pagination.totalItems}></ul>
+    ${paginator(pagination.totalItems, currentLimit, actualPage)}
+    `;
+
+    const ul = sitesList.querySelector('.my-sites-overview');
+    sitesList.append(ul);
```
Comment (icaraps) [inline blocks/dashboard/renderSiteList.js:62]: I don't understand why here you're appending the `ul` in `sitesList` ? Isn't it already a child of it ? Also why can't you use `safeText` instead of `textContent/innerText` and `value`?

File: blocks/dashboard/renderSiteList.js [hunk 2]
```diff
@@ -129,7 +146,9 @@ export default async function renderSites({ container, nav }) {
           <li data-owner="all"><button class="button selector action secondary ${owner === 'all' ? 'is-selected' : ''}">Owner: Anyone</button></li>
           <li data-owner="me"><button class="button selector action secondary ${owner === 'me' ? 'is-selected' : ''}">Owner: Me</button></li>
         </ul>`;
-  sites.innerHTML = `${filter}<input value="${search}" type="search" placeholder="Filter sites" class="filter-sites filter"><div class="sites-list"><section class="sites-list-dark-alley"></section><section class="sites-list-google-drive"></section></div>`;
+  sites.innerHTML = `${filter}<input type="search" placeholder="Filter sites" class="filter-sites filter"><div class="sites-list"><section class="sites-list-dark-alley"></section><section class="sites-list-google-drive"></section></div>`;
+  const filterSitesInput = sites.querySelector('.filter-sites');
+  filterSitesInput.value = search;
```
Comment (icaraps) [inline blocks/dashboard/renderSiteList.js:151]: Can't we use `safeText()` ?

File: blocks/site-details/renderCampaignsAnalytics.js [hunk 3]
```diff
@@ -172,14 +172,17 @@ export default async function renderCampaignsAnalytics({
         </div>
         
         <h2 id="email-details">Email details</h2>
-        <input value="${search}" type="search" placeholder="Filter" class="filter-email-details filter">
+        <input type="search" placeholder="Filter" class="filter-email-details filter">
```
Comment (icaraps) [inline blocks/site-details/renderCampaignsAnalytics.js:175]: Can't we use safeText ?

File: blocks/site-details/renderCampaignsAnalytics.js [hunk 4]
```diff
@@ -172,14 +172,17 @@ export default async function renderCampaignsAnalytics({
...
         <div class="email-details clusterize">
           ${renderSkeleton('campaign-tracking')}
         </div>
       `;
 
+  const emailFilter = container.querySelector('.filter-email-details');
+  emailFilter.value = search; // setting value here, XXS
```
Comment (icaraps) [inline blocks/site-details/renderCampaignsAnalytics.js:182]: It's XSS

File: blocks/site-details/renderSiteOverview.js [hunk 5]
```diff
@@ -54,7 +54,7 @@ export default async function renderSiteOverview({ container, nav, renderOptions
       </div>
       <div id="site-description" class="project-description card box">
         <strong>Site description</strong>
-        <span class="project-description description span">${projectDetails.projectDescription ?? ''}</span>
+        <span class="project-description description span"></span>
```
Comment (icaraps) [inline blocks/site-details/renderSiteOverview.js:57]: Can't we use safeText ?

File: blocks/site-details/renderSitePages.js [hunk 6]
```diff
@@ -38,7 +38,7 @@ export function renderTable({
 
       tableRow.dataset.path = item.path;
       tableRow.innerHTML = `
-        <td>${item.name}</td>
+        <td></td>
```
Comment (icaraps) [inline blocks/site-details/renderSitePages.js:41]: Can't we use safeText ?

File: blocks/site-details/renderSitePages.js [hunk 7]
```diff
@@ -49,6 +49,7 @@ export function renderTable({
           </div>
         </td>
       `;
+      tableRow.children[0].textContent = item.name; // setting name here, prevent XXS from doc name
```
Comment (icaraps) [inline blocks/site-details/renderSitePages.js:52]: It's XSS

File: blocks/site-details/renderSitePages.js [hunk 8]
```diff
@@ -82,7 +83,7 @@ export function renderTable({
     }
 
     tableRow.innerHTML = `
-      <td>${item.name}</td>
+      <td></td>
```
Comment (icaraps) [inline blocks/site-details/renderSitePages.js:86]: Can't we use safeText ?

File: blocks/wizard/wizard.js [hunk 9]
```diff
@@ -424,6 +428,7 @@ export default async function decorate(block) {
 
   createForm.onchange = () => {
     nameInput.value = nameInput.value.trim();
+    nameInput.value = sanitizeName(nameInput.value);
```
Comment (icaraps) [inline blocks/wizard/wizard.js:431]: You're setting the value twice ?

**Review by icaraps — CHANGES_REQUESTED** [review]

**Review by icaraps — APPROVED** [review]
